apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: osai-kube
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      initContainers:
        - name: init-db-config
          image: busybox
          command:
            [
              "sh",
              "-c",
              "cp /postgres-config/pg_hba.conf /postgresql-storage/pgdata/pg_hba.conf",
            ]
          volumeMounts:
            - name: postgres-config-volume
              mountPath: /postgres-config
            - name: postgresql-storage
              mountPath: /postgresql-storage
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: postgresql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
