apiVersion: v1
kind: Pod
metadata:
  name: gpu-diagnostic-pod
spec:
  containers:
    - name: cuda-toolkit
      image: nvidia/cuda:12.1.1-base-ubuntu22.04
      command: ["sleep", "infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1
      securityContext:
        privileged: true
  nodeSelector:
    pool: doodle
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
