apiVersion: apps/v1
kind: Deployment
metadata:
  name: doodle-deployment
  namespace: osai-kube
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: doodle
  template:
    metadata:
      labels:
        app: doodle
    spec:
      containers:
        - name: doodle
          image: us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/browserlab/doodle@sha256:147ab1a673ea53dd3ae4ae3822eaab362fea5e50c294ff3c661e12ddf891f4e4
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8001
        - name: gatekeeper
          image: quay.io/keycloak/keycloak-gatekeeper
          args:
            - --config=/etc/gatekeeper/config.yaml
            - --listen=0.0.0.0:3000
          volumeMounts:
            - name: gatekeeper-doodle-config
              mountPath: /etc/gatekeeper
          ports:
            - containerPort: 3000
      volumes:
        - name: gatekeeper-doodle-config
          secret:
            secretName: gatekeeper-doodle-secret
      nodeSelector:
        pool: doodle
