apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: osai-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.3
          args:
            - "start"
            - "--db=postgres"
            - "--db-url=jdbc:postgresql://postgresql.osai-kube.svc.cluster.local/keycloak"
            - "--db-username=keycloak"
            - "--db-password=${DB_PASSWORD}"
            - "--hostname=keycloak.moz8.net"
            - "--proxy=edge"
          env:
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: "postgresql.osai-kube.svc.cluster.local"
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_USER
              value: "keycloak"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_HTTPS_PORT
              value: "443"
            - name: KC_PROXY
              value: "passthrough"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 1
            periodSeconds: 10
