apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor-deployment
  namespace: osai-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervisor
  template:
    metadata:
      labels:
        app: supervisor
    spec:
      serviceAccountName: default # Specify the Service Account here
      containers:
        - name: supervisor
          image: us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/osai-kube/supervisor@sha256:6042f7cda309d41bf56f0d054e5cab3dd6aaf689e56380a5b1c973e3a512694f
          env:
            - name: ARTIFACT_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: registry-config
                  key: artifactRegistry
          ports:
            - containerPort: 5000
