apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor-deployment
  namespace: osai-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervisor
  template:
    metadata:
      labels:
        app: supervisor
    spec:
      serviceAccountName: default # Specify the Service Account here
      containers:
        - name: supervisor
          image: us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/osai-kube/supervisor@sha256:9cddf9d1138717df32c7f1f7c97e5763762b4e692a74b2b47b99a6d97c3ea58b
          imagePullPolicy: Always
          env:
            - name: ARTIFACT_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: registry-config
                  key: artifactRegistry
          ports:
            - containerPort: 5000
