apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: LoadBalancer
  loadBalancerIP: 34.69.32.38
  ports:
    - name: http
      port: 80
      targetPort: web
  selector:
    app: traefik
