apiVersion: v1
kind: Service
metadata:
  name: doodle-service
  namespace: osai-kube
spec:
  selector:
    app: doodle
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8001
    - name: gatekeeper
      protocol: TCP
      port: 3000
      targetPort: 3000
