apiVersion: apps/v1
kind: Deployment
metadata:
  name: doodle-deployment
  namespace: osai-kube
spec:
  replicas: 0 # Start with 0 replicas
  selector:
    matchLabels:
      app: doodle
  template:
    metadata:
      labels:
        app: doodle
    spec:
      containers:
        - name: doodle
          # image: $(ARTIFACT_REGISTRY)/browserlab/doodle@sha256:d5221baae78e78f44d2bdf74f570bb17c241de5ce25048149796c1bb7663f4f3
          image: $(ARTIFACT_REGISTRY)/browserlab/doodle@sha256:d5221baae78e78f44d2bdf74f570bb17c241de5ce25048149796c1bb7663f4f3
          resources:
            limits:
              nvidia.com/gpu: 1 # Assuming usage of NVIDIA GPUs
      nodeSelector:
        pool: doodle # Ensure this matches the label given to the nodes in the doodle node pool
