apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor-deployment
  namespace: osai-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervisor
  template:
    metadata:
      labels:
        app: supervisor
    spec:
      serviceAccountName: default # Specify the Service Account here
      containers:
        - name: supervisor
          image: $(ARTIFACT_REGISTRY)/osai-kube/supervisor:latest
          imagePullPolicy: Always
          env:
            - name: ARTIFACT_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: registry-config
                  key: registryUrl
          ports:
            - containerPort: 5000
