apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor-deployment
  namespace: osai-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervisor
  template:
    metadata:
      labels:
        app: supervisor
    spec:
      containers:
        - name: supervisor
          image: $(REGISTRY_URL)/osai-kube/supervisor:latest
          imagePullPolicy: Always
          env:
            - name: REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: registry-config
                  key: registryUrl
          ports:
            - containerPort: 5000 # Replace with the port your app uses, if different
