apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-users-config-map
  namespace: osai-kube
data:
  init-db-users.sh: |
    #!/bin/bash
    set -e

    # Function to create user and database with permissions on schema public
    create_user_and_db() {
        local user=$1
        local pass=$2
        local dbname=$3

        echo "Creating user $user, database $dbname, and granting permissions..."

        # Create user and database
        local create_db_sql
        create_db_sql+="CREATE ROLE \"$user\" WITH LOGIN PASSWORD '$pass'; "
        create_db_sql+="CREATE DATABASE \"$dbname\"; "
        create_db_sql+="GRANT ALL PRIVILEGES ON DATABASE \"$dbname\" TO \"$user\";"
        echo "$create_db_sql" | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER"

        # Grant permissions in the newly created database
        local grant_perms_sql
        grant_perms_sql+="GRANT ALL PRIVILEGES ON SCHEMA public TO \"$user\";"
        echo "$grant_perms_sql" | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$dbname"
    }

    KEYCLOAK_USER=$(cat /etc/secrets/keycloak/username)
    KEYCLOAK_PASS=$(cat /etc/secrets/keycloak/password)
    STORAGE_GATEWAY_USER=$(cat /etc/secrets/storage-gateway/username)
    STORAGE_GATEWAY_PASS=$(cat /etc/secrets/storage-gateway/password)

    # Create Keycloak user and database
    create_user_and_db $KEYCLOAK_USER $KEYCLOAK_PASS "keycloak"

    # Create Storage Gateway user and database
    create_user_and_db $STORAGE_GATEWAY_USER $STORAGE_GATEWAY_PASS "storage_gateway"
